// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"database/sql"
	"time"
)

type Comic struct {
	ID              string
	Title           string
	IssueNumber     int32
	PublicationDate time.Time
	Storyline       sql.NullString
	CoverArtUrl     sql.NullString
	Read            sql.NullBool
	UserID          sql.NullString
	UpdatedAt       sql.NullTime
}

type User struct {
	ID        string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	Name      string
	ApiKey    string
}

type UserComic struct {
	ID        int32
	UserID    sql.NullString
	ComicID   sql.NullString
	Favorite  sql.NullBool
	CreatedAt sql.NullTime
}
