// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"database/sql"
	"time"

	"github.com/sqlc-dev/pqtype"
)

type Manga struct {
	ID              string
	Status          interface{}
	UserID          sql.NullInt32
	Title           string
	IssueNumber     int32
	PublicationDate time.Time
	Storyline       sql.NullString
	CoverArtUrl     sql.NullString
	UpdatedAt       sql.NullTime
	Images          pqtype.NullRawMessage
	Authors         pqtype.NullRawMessage
	Serializations  pqtype.NullRawMessage
	Genres          pqtype.NullRawMessage
	ExplicitGenres  pqtype.NullRawMessage
	Themes          pqtype.NullRawMessage
	Demographics    pqtype.NullRawMessage
	Score           sql.NullFloat64
	ScoredBy        sql.NullInt32
	Rank            sql.NullInt32
	Popularity      sql.NullInt32
	Members         sql.NullInt32
	Favorites       sql.NullInt32
	Synopsis        sql.NullString
	Background      sql.NullString
	Relations       pqtype.NullRawMessage
	ExternalLinks   pqtype.NullRawMessage
}

type User struct {
	ID           string
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
	Username     string
	Email        string
	PasswordHash string
}
