version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080" 
    environment:
      - DATABASE_URL=${DATABASE_URL}
    env_file:
      - .env
    volumes:
      - .:/app
      
  frontend:
    build:
      context: ./frontend/mangabox
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000" 
    depends_on:
      - backend
    volumes:
      - ./frontend/mangabox:/app